const reduxConstants = {
  ADD_TODO_ACTION_SUCCESS: "ADD_TODO_ACTION_SUCCESS",
  UPDATE_TODO_ACTION_SUCCESS: "UPDATE_TODO_ACTION_SUCCESS",
  DELETE_TODO_ACTION_SUCCESS: "DELETE_TODO_ACTION_SUCCESS",
  DELETE_ALL_TODOs_ACTION_SUCCESS: "DELETE_ALL_TODOs_ACTION_SUCCESS",
  COMPLETE_TODO_ACTION_SUCCESS: "COMPLETE_TODO_ACTION_SUCCESS",
};

export default reduxConstants;
