const reduxConstants = {
  TODO_ADD_ACTION: "TO_ADD_ACTION",
  TODO_UPDATE_ACTION: "TO_UPDATE_ACTION",
  TODO_DELETE_ACTION: "TO_DELETE_ACTION",
  ALL_TODO_DELETE_ACTION: "ALL_TODO_DELETE_ACTION",
  CALL_API_LOAD: "CALL_API_LOAD",
  CALL_API_SUCCESS: "CALL_API_SUCCESS",
  CALL_API_FAIL: "CALL_API_FAIL",
};

export default reduxConstants;
